version: "3.9"

services:

  postgres:
    image: postgres:15.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pattern_core_network
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    environment:
      MODULE_NAME: src.main
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    networks:
      - pattern_core_network

volumes:
  pg_data:

networks:
  pattern_core_network:
    external: true
