name: Dev Build, Push and Deploy

on:
  push:
    branches:
      - develop
    # # Only trigger if changes occur in the 'api' folder
    # paths:
    #   - "api/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: patterntechnology/pattern-core-api:latest
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST_DEV }}
          username: ${{ secrets.SERVER_USER_DEV }}
          key: ${{ secrets.SERVER_SSH_KEY_DEV }}
          port: ${{ secrets.SERVER_SSH_PORT_DEV }}
          script: |
            echo "Pulling the latest Docker image..."
            docker pull patterntechnology/pattern-core-api:latest

            echo "Stopping and removing the old container (if exists)..."
            docker stop pattern-core-api || true
            docker rm pattern-core-api || true

            echo "Starting a new container with environment variables..."
            docker run -d \
              --name pattern-core-api \
              --network pattern_core_network \
              -p 5001:8000 \
              -e POSTGRES_HOST=api-postgres-1 \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_DB=pattern-core \
              -e POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e QDRANT_HOST=http://qdrant:6333 \
              -e QDRANT_COLLECTION=pattern-core \
              -e MORALIS_API_KEY=${{ secrets.MORALIS_API_KEY }} \
              -e ETHER_SCAN_API_KEY=${{ secrets.ETHER_SCAN_API_KEY }} \
              -e GOLDRUSH_API_KEY=${{ secrets.GOLDRUSH_API_KEY }} \
              -e LLM_PROVIDER=${{ secrets.LLM_PROVIDER }} \
              -e LLM_MODEL=${{ secrets.LLM_MODEL }} \
              -e LLM_API_KEY=${{ secrets.LLM_API_KEY }} \
              -e AGENTS=${{ secrets.AGENTS }} \
              -e SENTRY_DNS=${{ secrets.SENTRY_DNS }} \
              -e APP_NAME=${{ secrets.APP_NAME }} \
              -e LOG_FILE_PATH=${{ secrets.LOG_FILE_PATH }} \
              -e LOG_BACKUP_COUNT=${{ secrets.LOG_BACKUP_COUNT }} \
              -e LOG_MAX_BYTES=${{ secrets.LOG_MAX_BYTES }} \
              -e ETHER_SCAN_API_KEY=${{ secrets.ETHER_SCAN_API_KEY }} \
              -e ARBI_SCAN_API_KEY=${{ secrets.ARBI_SCAN_API_KEY }} \
              -e BASE_SCAN_API_KEY=${{ secrets.BASE_SCAN_API_KEY }} \
              -e POLYGON_SCAN_API_KEY=${{ secrets.POLYGON_SCAN_API_KEY }} \
              -e FTM_SCAN_API_KEY=${{ secrets.FTM_SCAN_API_KEY }} \
              -e ETH_RPC=${{ vars.ETH_RPC }} \
              -e ARBITRUM_ONE_RPC=${{ vars.ARBITRUM_ONE_RPC }} \
              -e POLYGON_RPC=${{ vars.POLYGON_RPC }} \
              -e FANTOM_RPC=${{ vars.FANTOM_RPC }} \
              -e BASE_RPC=${{ vars.BASE_RPC }} \
              -e SOLSCAN_API_KEY=${{ secrets.SOLSCAN_API_KEY }} \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              -e POKT_API_KEY=${{ secrets.POKT_API_KEY }} \
              -e POKT_GRAPH_SCHEMA_PATH=${{ vars.POKT_GRAPH_SCHEMA_PATH }} \
              -e POKT_GRAPH_ENDPOINT=${{ vars.POKT_GRAPH_ENDPOINT }} \
              patterntechnology/pattern-core-api:latest

            # Wait a few seconds to give the container time to start
            sleep 5

            # Verify if the container is running
            if docker ps | grep -q pattern-core-api; then
              echo "Container is running successfully. Removing unused images..."
              docker image prune -f
            else
              echo "Container failed to start. Skipping image cleanup."
            fi
